DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS posts;

CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	user_name TEXT NOT NULL UNIQUE
 );

CREATE TABLE posts (
	id SERIAL PRIMARY KEY,
	body VARCHAR(142) NOT NULL,
	user_id INTEGER NOT NULL	
);